/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Book = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'genre' : IDL.Text,
  'coverUrl' : IDL.Text,
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'bookId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Review = IDL.Record({
  'userId' : IDL.Principal,
  'bookId' : IDL.Nat,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBook' : IDL.Func([Book], [], []),
  'addChapter' : IDL.Func([Chapter], [], []),
  'addFavorite' : IDL.Func([IDL.Nat], [], []),
  'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBook' : IDL.Func([IDL.Nat], [], []),
  'deleteChapter' : IDL.Func([IDL.Nat], [], []),
  'filterByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Float64)], ['query']),
  'getBookById' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapterById' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
  'getChaptersByBookId' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getReadingProgress' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'getReviewsByBookId' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'removeFavorite' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'updateBook' : IDL.Func([IDL.Nat, Book], [], []),
  'updateChapter' : IDL.Func([IDL.Nat, Chapter], [], []),
  'updateReadingProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Book = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'genre' : IDL.Text,
    'coverUrl' : IDL.Text,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'bookId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Review = IDL.Record({
    'userId' : IDL.Principal,
    'bookId' : IDL.Nat,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBook' : IDL.Func([Book], [], []),
    'addChapter' : IDL.Func([Chapter], [], []),
    'addFavorite' : IDL.Func([IDL.Nat], [], []),
    'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBook' : IDL.Func([IDL.Nat], [], []),
    'deleteChapter' : IDL.Func([IDL.Nat], [], []),
    'filterByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Float64)], ['query']),
    'getBookById' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapterById' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
    'getChaptersByBookId' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getReadingProgress' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'getReviewsByBookId' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'removeFavorite' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'updateBook' : IDL.Func([IDL.Nat, Book], [], []),
    'updateChapter' : IDL.Func([IDL.Nat, Chapter], [], []),
    'updateReadingProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };