/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'author' : string,
  'genre' : string,
  'coverUrl' : string,
}
export interface Chapter {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'bookId' : bigint,
}
export interface Review {
  'userId' : Principal,
  'bookId' : bigint,
  'comment' : string,
  'rating' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBook' : ActorMethod<[Book], undefined>,
  'addChapter' : ActorMethod<[Chapter], undefined>,
  'addFavorite' : ActorMethod<[bigint], undefined>,
  'addReview' : ActorMethod<[bigint, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBook' : ActorMethod<[bigint], undefined>,
  'deleteChapter' : ActorMethod<[bigint], undefined>,
  'filterByGenre' : ActorMethod<[string], Array<Book>>,
  'getAverageRating' : ActorMethod<[bigint], [] | [number]>,
  'getBookById' : ActorMethod<[bigint], [] | [Book]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapterById' : ActorMethod<[bigint], [] | [Chapter]>,
  'getChaptersByBookId' : ActorMethod<[bigint], Array<Chapter>>,
  'getFavorites' : ActorMethod<[], Array<bigint>>,
  'getReadingProgress' : ActorMethod<[bigint], [] | [bigint]>,
  'getReviewsByBookId' : ActorMethod<[bigint], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllBooks' : ActorMethod<[], Array<Book>>,
  'removeFavorite' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBooks' : ActorMethod<[string], Array<Book>>,
  'updateBook' : ActorMethod<[bigint, Book], undefined>,
  'updateChapter' : ActorMethod<[bigint, Chapter], undefined>,
  'updateReadingProgress' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];